library(ggplot2)
library(gridExtra)
grade_input = as.data.frame(read.csv("C:/Users/Aniket/Desktop/BI/3/grades1.csv"))
print(grade_input)
head(grade_input)
print(ncol(grade_input))
print(nrow(grade_input))
kmset<-as.matrix(grade_input[,c("Student", "English", "Math", "Science")])
kmdata <- kmset[,c(2:4)]
print(kmdata)
wss <- numeric(10)
print(wss)
for ( k in 1:10) wss[k]= sum(kmeans(kmdata,centers = k,nstart=25)$withinss)
print(wss)
plot(1:10,wss,xlab = "cluster",ylab="WSS")
k.3<-kmeans(kmdata,centers = 3,nstart=30)
k.3
df <- as.data.frame(grade_input[,2:4])
df$cluster <- factor(k.3$cluster)
print(df)
plot1 <- as.data.frame(grade_input[,2:4])
plot1$cluster <- factor(k.3$cluster)
centers<- as.data.frame(k.3$centers)
g1 <- ggplot(data=df, aes(x=English, y=Math, color=cluster ))+geom_point() + theme(legend.position="right") +geom_point(data=centers,aes(x=English,y=Math, color=as.factor(c(1,2,3))),size=10, alpha=.3, show.legend = FALSE)
g2 <- ggplot(data=df, aes(x=English, y=Science, color=cluster)) +geom_point() +geom_point(data=centers,aes(x=English,y=Science, color=as.factor(c(1,2,3))),size=10, alpha=.3, show.legend = FALSE)
g3 <- ggplot(data=df, aes(x=Math, y=Science, color=cluster)) +geom_point() +geom_point(data=centers,aes(x=Math,y=Science, color=as.factor(c(1,2,3))),size=10, alpha=.3, show.legend =  FALSE)
tmp <- ggplot_gtable(ggplot_build(g1))
grid.arrange(g1,g2,g3,ncol = 1, nrow = 3)

